// Mock data for demo mode (when DB is unavailable)
import { DY_PATIL_MAP } from './venueMap';

export const SEED_EVENT_ID = 'event-ipl-2025-mi-csk';
export const SEED_VENUE_ID = 'venue-dy-patil';

export const MOCK_VENUES = [
  {
    id: SEED_VENUE_ID,
    name: 'DY Patil Stadium',
    city: 'Navi Mumbai',
    address: 'DY Patil Sports Academy, Nerul, Navi Mumbai, Maharashtra 400706',
    capacity: 55000,
    lat: 19.0460,
    lng: 73.0165,
    imageUrl: null,
    mapConfig: DY_PATIL_MAP,
  },
  {
    id: 'venue-wankhede',
    name: 'Wankhede Stadium',
    city: 'Mumbai',
    address: 'D Rd, Churchgate, Mumbai, Maharashtra 400020',
    capacity: 33108,
    lat: 18.9375,
    lng: 72.8252,
    imageUrl: null,
    mapConfig: {},
  },
  {
    id: 'venue-jln',
    name: 'JLN Stadium',
    city: 'New Delhi',
    address: 'Bhishma Pitamah Marg, New Delhi, Delhi 110003',
    capacity: 75000,
    lat: 28.5836,
    lng: 77.2333,
    imageUrl: null,
    mapConfig: {},
  },
];

export const MOCK_EVENTS = [
  {
    id: SEED_EVENT_ID,
    venueId: SEED_VENUE_ID,
    name: 'IPL 2025 — MI vs CSK',
    description: 'Mumbai Indians vs Chennai Super Kings — IPL 2025 Season Opener at DY Patil Stadium',
    date: new Date('2025-04-19T19:30:00+05:30'),
    startTime: new Date('2025-04-19T19:30:00+05:30'),
    endTime: new Date('2025-04-19T23:30:00+05:30'),
    bannerUrl: null,
    status: 'LIVE',
    emergencyActive: false,
    simulationPhase: 'FILLING',
    venue: MOCK_VENUES[0],
    zones: DY_PATIL_MAP.zones.map(z => ({
      id: z.id,
      name: z.name,
      label: z.label,
      maxCapacity: z.maxCapacity,
      currentCount: Math.round(z.maxCapacity * 0.45),
      densityLevel: 'MEDIUM',
      evacuationActive: false,
      exitPaths: z.exitPaths,
      lat: z.lat,
      lng: z.lng,
      polygonCoords: z.polygonCoords,
      zoneType: z.zoneType,
    })),
    gates: DY_PATIL_MAP.gates.map(g => ({
      id: g.id,
      name: g.name,
      label: g.label,
      zoneId: g.zoneId,
      status: 'OPEN',
      currentQueueCount: 320,
      avgWaitMinutes: 6,
      throughputPerMinute: g.defaultThroughput,
      staffCount: 4,
      isVip: g.isVip,
    })),
  },
  {
    id: 'event-isl-2025-fc-goa',
    venueId: 'venue-jln',
    name: 'ISL 2025 — FC Goa vs Mumbai City',
    description: 'Indian Super League — FC Goa vs Mumbai City FC at JLN Stadium, New Delhi',
    date: new Date('2025-04-25T20:00:00+05:30'),
    startTime: new Date('2025-04-25T20:00:00+05:30'),
    endTime: new Date('2025-04-25T22:30:00+05:30'),
    bannerUrl: null,
    status: 'UPCOMING',
    emergencyActive: false,
    simulationPhase: 'GATES_OPEN',
    venue: MOCK_VENUES[2],
    zones: [],
    gates: [],
  },
  {
    id: 'event-concert-2025',
    venueId: 'venue-wankhede',
    name: 'Arijit Singh Live — The Emotional Tour',
    description: "Arijit Singh's blockbuster live concert at Wankhede Stadium, Mumbai",
    date: new Date('2025-05-10T18:00:00+05:30'),
    startTime: new Date('2025-05-10T18:00:00+05:30'),
    endTime: new Date('2025-05-10T22:00:00+05:30'),
    bannerUrl: null,
    status: 'UPCOMING',
    emergencyActive: false,
    simulationPhase: 'GATES_OPEN',
    venue: MOCK_VENUES[1],
    zones: [],
    gates: [],
  },
];

export const MOCK_USERS = [
  { id: 'seed-manager-1', name: 'Arjun Sharma', email: 'manager@venueflow.ai', role: 'MANAGER', avatarUrl: null },
  { id: 'seed-fan-1', name: 'Priya Patel', email: 'fan1@venueflow.ai', role: 'FAN', avatarUrl: null },
  { id: 'seed-fan-2', name: 'Rahul Singh', email: 'fan2@venueflow.ai', role: 'FAN', avatarUrl: null },
  { id: 'seed-staff-1', name: 'Ravi Kumar', email: 'staff1@venueflow.ai', role: 'STAFF', avatarUrl: null },
  { id: 'seed-admin-1', name: 'Admin', email: 'admin@venueflow.ai', role: 'ADMIN', avatarUrl: null },
];

export const MOCK_TICKET = {
  id: 'ticket-seed-001',
  eventId: SEED_EVENT_ID,
  userId: 'seed-fan-1',
  seatNumber: 'N-Block-Row-G-Seat-14',
  gateAssigned: 'Gate B',
  standAssigned: 'North Stand',
  qrCode: 'VF-IPL25-MICK-N-G14-001',
  status: 'ACTIVE',
  event: MOCK_EVENTS[0],
};

export const MOCK_ALERTS = [
  {
    id: 'alert-001',
    eventId: SEED_EVENT_ID,
    zoneId: 'zone-gate-c',
    zoneName: 'Gate C',
    severity: 'WARNING',
    message: 'WARNING: Gate C queue wait exceeds 12 minutes (14 min). Consider diverting fans to Gate B.',
    aiGenerated: false,
    resolved: false,
    createdAt: new Date(Date.now() - 5 * 60 * 1000),
  },
  {
    id: 'alert-002',
    eventId: SEED_EVENT_ID,
    zoneId: 'zone-food-court-central',
    zoneName: 'Food Court Central',
    severity: 'INFO',
    message: 'Food Court Central approaching 75% capacity ahead of expected halftime surge.',
    aiGenerated: false,
    resolved: false,
    createdAt: new Date(Date.now() - 12 * 60 * 1000),
  },
];
